### ISSUE TITLE
`yarn build` doesn't work on Windows

### ISSUE THREAD

**Issue by gangal86** [fingerprintjs/fingerprintjs#981]
When I run the command `yarn build` I get an error:
```
$ yarn build
yarn run v1.22.21
$ rimraf dist && rollup -c rollup.config.ts --configPlugin '@rollup/plugin-typescript={tsconfig:`tsconfig.rollupConfig.json`}'
[!] Error: Invalid --plugin argument format: "'@rollup/plugin-typescript={tsconfig:`tsconfig.rollupConfig.json`}'"
    at loadAndRegisterPlugin (D:\fingerprint-test\fingerprintjs\node_modules\rollup\dist\shared\loadConfigFile.js:367:19)
    at addPluginsFromCommandOption (D:\fingerprint-test\fingerprintjs\node_modules\rollup\dist\shared\loadConfigFile.js:339:23)
    at loadTranspiledConfigFile (D:\fingerprint-test\fingerprintjs\node_modules\rollup\dist\shared\loadConfigFile.js:497:5)
    at getConfigFileExport (D:\fingerprint-test\fingerprintjs\node_modules\rollup\dist\shared\loadConfigFile.js:447:20)
    at Object.loadConfigFile (D:\fingerprint-test\fingerprintjs\node_modules\rollup\dist\shared\loadConfigFile.js:428:59)
    at getConfigs (D:\fingerprint-test\fingerprintjs\node_modules\rollup\dist\bin\rollup:1684:39)
    at runRollup (D:\fingerprint-test\fingerprintjs\node_modules\rollup\dist\bin\rollup:1661:43)


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Finesse** [comment]
Hey Roman. What OS do you run it on?

**Comment by gangal86** [comment]
> Hey Roman. What OS do you run it on?
Hey Sergey. I'm working on Windows 10

**Comment by Finesse** [comment]
@dj-stormtrooper Looks like your recent fix to Fingerprint Pro will help here. Could you please apply it to FingerprintJS?

**Comment by dj-stormtrooper** [comment]
Sure, I created PR https://github.com/fingerprintjs/fingerprintjs/pull/985

@gangal86 feel free to try running `yarn build` on this PR before release in case you find any other issues with Windows that we can help with

**Comment by gangal86** [comment]
> Sure, I created PR #985
> 
> @gangal86 feel free to try running `yarn build` on this PR before release in case you find any other issues with Windows that we can help with

I tried running yarn build on Windows. Everything works perfectly. Thank you!
